

POST https://crud-operations-backand.onrender.com/usuarios
Content-type: application/json

{
  "nome": "João da Silva",
  "email": "joaodasilva@gmail.com",
  "celular": "44 91234-1234",
  "RA": "a2440962",
  "data_de_admissão": "12-04-2005",
  "numero_da_conta": "12-04-2005",
  "numero_da_conta": "12-04-2005",
}

###

POST https://crud-operations-backand.onrender.com/usuarios
Content-type: application/json

{
  "nome": "Maria Freitas",
  "email": "mariafreitas@gmail.com",
  "celular": "44 94321-4321"
}

###

GET https://crud-operations-backand.onrender.com/usuarios

###

GET https://crud-operations-backand.onrender.com/usuarios?nome=joão

###

PUT https://crud-operations-backand.onrender.com/usuarios/b8093df3-d630-429c-acb4-36b6ee74c560
Content-type: application/json
Accept-Language: pt

{
  "nome": "João da Silva",
  "email": "joaodasilva2@gmail.com",
  "celular": "44 91234-1234"
}

###

DELETE https://crud-operations-backand.onrender.com/usuarios/12
